version: '3'
services:
  app:
    container_name: pinner
    build: .
    ports:
      - '80:3000'
    links:
      - db
  db:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
